FORMAT: 1A

# API Errors

This document defines all possible errors in the User/Track API.

## 400 - Bad Request [/bad_request/]

The server cannot or will not process the request due to something that is perceived to be a client error.

### not valid [GET /not_valid/]

+ Response 400 (application/json)

        {
            "code": "invalid_argument",
            "msg": "id must be a valid uuid",
            "meta": {
                "argument": "id"
            }
        }

### required [GET /required/]

+ Response 400 (application/json)

        {
            "code": "invalid_argument",
            "msg": "email is required",
            "meta": {
                "argument": "email"
            }
        }

## 404 - Not Found [/not_found/]

The server did not find a representation for the target resource or is not willing to disclose that one exists.

### does not exist [GET /does_not_exist]

+ Response 404 (application/json)

        {
            "code": "not_found",
            "msg": "track_group does not exist"
        }

### reference not found [GET /reference_not_found]

+ Response 404 (application/json)

        {
            "code": "not_found",
            "msg": "insert or update on table \"tracks\" violates foreign key constraint \"tracks_creator_id_fkey\""
        }

## 404 - Bad Route [/bad_route/]

### bad route [GET /bad_route/]

+ Response 404 (application/json)

        {
            "code": "bad_route",
            "msg": "no handler for path \"/twirp/resonate.api.user.TagService/SearchGenre\"",
            "meta": {
                "twirp_invalid_route": "POST /twirp/resonate.api.user.TagService/SearchGenre"
            }
        }

## 409 - Conflict [/conflict/]
The request could not be completed due to a conflict with the current state of the target resource.

### already exists [GET /already_exists/]

+ Response 409 (application/json)

        {
            "code": "already_exists",
            "msg": "username"
        }

## 500 - Internal Server Error [/internal_server_error/]

The server encountered an unexpected condition which prevented it from fulfilling the request.

### unknown [GET /unknown/]

+ Response 500 (application/json)

        {
            "code": "unknown",
            "msg": "example error message"
        }
