// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/usergroup/service.proto

package usergroup

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import track "user-api/rpc/track"
import user "user-api/rpc/user"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserGroup struct {
	Id                   string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DisplayName          string                     `protobuf:"bytes,2,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	Description          string                     `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	ShortBio             string                     `protobuf:"bytes,4,opt,name=short_bio,json=shortBio" json:"short_bio,omitempty"`
	Avatar               []byte                     `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Banner               []byte                     `protobuf:"bytes,6,opt,name=banner,proto3" json:"banner,omitempty"`
	OwnerId              string                     `protobuf:"bytes,7,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
	Type                 *GroupTaxonomy             `protobuf:"bytes,8,opt,name=type" json:"type,omitempty"`
	Followers            []*user.User               `protobuf:"bytes,9,rep,name=followers" json:"followers,omitempty"`
	Members              []*UserGroup               `protobuf:"bytes,10,rep,name=members" json:"members,omitempty"`
	MemberOfGroups       []*UserGroup               `protobuf:"bytes,11,rep,name=memberOfGroups" json:"memberOfGroups,omitempty"`
	Links                []*Link                    `protobuf:"bytes,12,rep,name=links" json:"links,omitempty"`
	Tags                 []*track.Tag               `protobuf:"bytes,13,rep,name=tags" json:"tags,omitempty"`
	Address              *user.StreetAddress        `protobuf:"bytes,14,opt,name=address" json:"address,omitempty"`
	Privacy              *Privacy                   `protobuf:"bytes,16,opt,name=privacy" json:"privacy,omitempty"`
	RecommendedArtists   []*track.RelatedUserGroup  `protobuf:"bytes,17,rep,name=recommended_artists,json=recommendedArtists" json:"recommended_artists,omitempty"`
	FeaturedTrackGroup   *track.RelatedTrackGroup   `protobuf:"bytes,18,opt,name=featured_track_group,json=featuredTrackGroup" json:"featured_track_group,omitempty"`
	TrackGroups          []*track.RelatedTrackGroup `protobuf:"bytes,19,rep,name=track_groups,json=trackGroups" json:"track_groups,omitempty"`
	HighlightedTracks    []*track.Track             `protobuf:"bytes,20,rep,name=highlighted_tracks,json=highlightedTracks" json:"highlighted_tracks,omitempty"`
	GroupEmailAddress    string                     `protobuf:"bytes,22,opt,name=group_email_address,json=groupEmailAddress" json:"group_email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UserGroup) Reset()         { *m = UserGroup{} }
func (m *UserGroup) String() string { return proto.CompactTextString(m) }
func (*UserGroup) ProtoMessage()    {}
func (*UserGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{0}
}
func (m *UserGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroup.Unmarshal(m, b)
}
func (m *UserGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroup.Marshal(b, m, deterministic)
}
func (dst *UserGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroup.Merge(dst, src)
}
func (m *UserGroup) XXX_Size() int {
	return xxx_messageInfo_UserGroup.Size(m)
}
func (m *UserGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroup.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroup proto.InternalMessageInfo

func (m *UserGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserGroup) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserGroup) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UserGroup) GetShortBio() string {
	if m != nil {
		return m.ShortBio
	}
	return ""
}

func (m *UserGroup) GetAvatar() []byte {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *UserGroup) GetBanner() []byte {
	if m != nil {
		return m.Banner
	}
	return nil
}

func (m *UserGroup) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *UserGroup) GetType() *GroupTaxonomy {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *UserGroup) GetFollowers() []*user.User {
	if m != nil {
		return m.Followers
	}
	return nil
}

func (m *UserGroup) GetMembers() []*UserGroup {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *UserGroup) GetMemberOfGroups() []*UserGroup {
	if m != nil {
		return m.MemberOfGroups
	}
	return nil
}

func (m *UserGroup) GetLinks() []*Link {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *UserGroup) GetTags() []*track.Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *UserGroup) GetAddress() *user.StreetAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *UserGroup) GetPrivacy() *Privacy {
	if m != nil {
		return m.Privacy
	}
	return nil
}

func (m *UserGroup) GetRecommendedArtists() []*track.RelatedUserGroup {
	if m != nil {
		return m.RecommendedArtists
	}
	return nil
}

func (m *UserGroup) GetFeaturedTrackGroup() *track.RelatedTrackGroup {
	if m != nil {
		return m.FeaturedTrackGroup
	}
	return nil
}

func (m *UserGroup) GetTrackGroups() []*track.RelatedTrackGroup {
	if m != nil {
		return m.TrackGroups
	}
	return nil
}

func (m *UserGroup) GetHighlightedTracks() []*track.Track {
	if m != nil {
		return m.HighlightedTracks
	}
	return nil
}

func (m *UserGroup) GetGroupEmailAddress() string {
	if m != nil {
		return m.GroupEmailAddress
	}
	return ""
}

type TrackAnalytics struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	TotalPlays           int32    `protobuf:"varint,3,opt,name=total_plays,json=totalPlays" json:"total_plays,omitempty"`
	PaidPlays            int32    `protobuf:"varint,4,opt,name=paid_plays,json=paidPlays" json:"paid_plays,omitempty"`
	FreePlays            int32    `protobuf:"varint,5,opt,name=free_plays,json=freePlays" json:"free_plays,omitempty"`
	TotalCredits         float32  `protobuf:"fixed32,6,opt,name=total_credits,json=totalCredits" json:"total_credits,omitempty"`
	UserGroupCredits     float32  `protobuf:"fixed32,7,opt,name=user_group_credits,json=userGroupCredits" json:"user_group_credits,omitempty"`
	ResonateCredits      float32  `protobuf:"fixed32,8,opt,name=resonate_credits,json=resonateCredits" json:"resonate_credits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackAnalytics) Reset()         { *m = TrackAnalytics{} }
func (m *TrackAnalytics) String() string { return proto.CompactTextString(m) }
func (*TrackAnalytics) ProtoMessage()    {}
func (*TrackAnalytics) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{1}
}
func (m *TrackAnalytics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackAnalytics.Unmarshal(m, b)
}
func (m *TrackAnalytics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackAnalytics.Marshal(b, m, deterministic)
}
func (dst *TrackAnalytics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackAnalytics.Merge(dst, src)
}
func (m *TrackAnalytics) XXX_Size() int {
	return xxx_messageInfo_TrackAnalytics.Size(m)
}
func (m *TrackAnalytics) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackAnalytics.DiscardUnknown(m)
}

var xxx_messageInfo_TrackAnalytics proto.InternalMessageInfo

func (m *TrackAnalytics) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TrackAnalytics) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TrackAnalytics) GetTotalPlays() int32 {
	if m != nil {
		return m.TotalPlays
	}
	return 0
}

func (m *TrackAnalytics) GetPaidPlays() int32 {
	if m != nil {
		return m.PaidPlays
	}
	return 0
}

func (m *TrackAnalytics) GetFreePlays() int32 {
	if m != nil {
		return m.FreePlays
	}
	return 0
}

func (m *TrackAnalytics) GetTotalCredits() float32 {
	if m != nil {
		return m.TotalCredits
	}
	return 0
}

func (m *TrackAnalytics) GetUserGroupCredits() float32 {
	if m != nil {
		return m.UserGroupCredits
	}
	return 0
}

func (m *TrackAnalytics) GetResonateCredits() float32 {
	if m != nil {
		return m.ResonateCredits
	}
	return 0
}

type ArtistTrackAnalytics struct {
	Tracks               []*TrackAnalytics `protobuf:"bytes,1,rep,name=tracks" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ArtistTrackAnalytics) Reset()         { *m = ArtistTrackAnalytics{} }
func (m *ArtistTrackAnalytics) String() string { return proto.CompactTextString(m) }
func (*ArtistTrackAnalytics) ProtoMessage()    {}
func (*ArtistTrackAnalytics) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{2}
}
func (m *ArtistTrackAnalytics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtistTrackAnalytics.Unmarshal(m, b)
}
func (m *ArtistTrackAnalytics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtistTrackAnalytics.Marshal(b, m, deterministic)
}
func (dst *ArtistTrackAnalytics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtistTrackAnalytics.Merge(dst, src)
}
func (m *ArtistTrackAnalytics) XXX_Size() int {
	return xxx_messageInfo_ArtistTrackAnalytics.Size(m)
}
func (m *ArtistTrackAnalytics) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtistTrackAnalytics.DiscardUnknown(m)
}

var xxx_messageInfo_ArtistTrackAnalytics proto.InternalMessageInfo

func (m *ArtistTrackAnalytics) GetTracks() []*TrackAnalytics {
	if m != nil {
		return m.Tracks
	}
	return nil
}

type LabelTrackAnalytics struct {
	Artists              []*LabelTrackAnalytics_ArtistTrackAnalytics `protobuf:"bytes,1,rep,name=artists" json:"artists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *LabelTrackAnalytics) Reset()         { *m = LabelTrackAnalytics{} }
func (m *LabelTrackAnalytics) String() string { return proto.CompactTextString(m) }
func (*LabelTrackAnalytics) ProtoMessage()    {}
func (*LabelTrackAnalytics) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{3}
}
func (m *LabelTrackAnalytics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelTrackAnalytics.Unmarshal(m, b)
}
func (m *LabelTrackAnalytics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelTrackAnalytics.Marshal(b, m, deterministic)
}
func (dst *LabelTrackAnalytics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelTrackAnalytics.Merge(dst, src)
}
func (m *LabelTrackAnalytics) XXX_Size() int {
	return xxx_messageInfo_LabelTrackAnalytics.Size(m)
}
func (m *LabelTrackAnalytics) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelTrackAnalytics.DiscardUnknown(m)
}

var xxx_messageInfo_LabelTrackAnalytics proto.InternalMessageInfo

func (m *LabelTrackAnalytics) GetArtists() []*LabelTrackAnalytics_ArtistTrackAnalytics {
	if m != nil {
		return m.Artists
	}
	return nil
}

type LabelTrackAnalytics_ArtistTrackAnalytics struct {
	Artist               *track.RelatedUserGroup `protobuf:"bytes,1,opt,name=artist" json:"artist,omitempty"`
	Tracks               []*TrackAnalytics       `protobuf:"bytes,2,rep,name=tracks" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LabelTrackAnalytics_ArtistTrackAnalytics) Reset() {
	*m = LabelTrackAnalytics_ArtistTrackAnalytics{}
}
func (m *LabelTrackAnalytics_ArtistTrackAnalytics) String() string { return proto.CompactTextString(m) }
func (*LabelTrackAnalytics_ArtistTrackAnalytics) ProtoMessage()    {}
func (*LabelTrackAnalytics_ArtistTrackAnalytics) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{3, 0}
}
func (m *LabelTrackAnalytics_ArtistTrackAnalytics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelTrackAnalytics_ArtistTrackAnalytics.Unmarshal(m, b)
}
func (m *LabelTrackAnalytics_ArtistTrackAnalytics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelTrackAnalytics_ArtistTrackAnalytics.Marshal(b, m, deterministic)
}
func (dst *LabelTrackAnalytics_ArtistTrackAnalytics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelTrackAnalytics_ArtistTrackAnalytics.Merge(dst, src)
}
func (m *LabelTrackAnalytics_ArtistTrackAnalytics) XXX_Size() int {
	return xxx_messageInfo_LabelTrackAnalytics_ArtistTrackAnalytics.Size(m)
}
func (m *LabelTrackAnalytics_ArtistTrackAnalytics) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelTrackAnalytics_ArtistTrackAnalytics.DiscardUnknown(m)
}

var xxx_messageInfo_LabelTrackAnalytics_ArtistTrackAnalytics proto.InternalMessageInfo

func (m *LabelTrackAnalytics_ArtistTrackAnalytics) GetArtist() *track.RelatedUserGroup {
	if m != nil {
		return m.Artist
	}
	return nil
}

func (m *LabelTrackAnalytics_ArtistTrackAnalytics) GetTracks() []*TrackAnalytics {
	if m != nil {
		return m.Tracks
	}
	return nil
}

type UserGroupTrackAnalytics struct {
	// Types that are valid to be assigned to TrackAnalytics:
	//	*UserGroupTrackAnalytics_ArtistTrackAnalytics
	//	*UserGroupTrackAnalytics_LabelTrackAnalytics
	TrackAnalytics       isUserGroupTrackAnalytics_TrackAnalytics `protobuf_oneof:"track_analytics"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *UserGroupTrackAnalytics) Reset()         { *m = UserGroupTrackAnalytics{} }
func (m *UserGroupTrackAnalytics) String() string { return proto.CompactTextString(m) }
func (*UserGroupTrackAnalytics) ProtoMessage()    {}
func (*UserGroupTrackAnalytics) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{4}
}
func (m *UserGroupTrackAnalytics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroupTrackAnalytics.Unmarshal(m, b)
}
func (m *UserGroupTrackAnalytics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroupTrackAnalytics.Marshal(b, m, deterministic)
}
func (dst *UserGroupTrackAnalytics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroupTrackAnalytics.Merge(dst, src)
}
func (m *UserGroupTrackAnalytics) XXX_Size() int {
	return xxx_messageInfo_UserGroupTrackAnalytics.Size(m)
}
func (m *UserGroupTrackAnalytics) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroupTrackAnalytics.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroupTrackAnalytics proto.InternalMessageInfo

type isUserGroupTrackAnalytics_TrackAnalytics interface {
	isUserGroupTrackAnalytics_TrackAnalytics()
}

type UserGroupTrackAnalytics_ArtistTrackAnalytics struct {
	ArtistTrackAnalytics *ArtistTrackAnalytics `protobuf:"bytes,1,opt,name=artist_track_analytics,json=artistTrackAnalytics,oneof"`
}
type UserGroupTrackAnalytics_LabelTrackAnalytics struct {
	LabelTrackAnalytics *LabelTrackAnalytics `protobuf:"bytes,2,opt,name=label_track_analytics,json=labelTrackAnalytics,oneof"`
}

func (*UserGroupTrackAnalytics_ArtistTrackAnalytics) isUserGroupTrackAnalytics_TrackAnalytics() {}
func (*UserGroupTrackAnalytics_LabelTrackAnalytics) isUserGroupTrackAnalytics_TrackAnalytics()  {}

func (m *UserGroupTrackAnalytics) GetTrackAnalytics() isUserGroupTrackAnalytics_TrackAnalytics {
	if m != nil {
		return m.TrackAnalytics
	}
	return nil
}

func (m *UserGroupTrackAnalytics) GetArtistTrackAnalytics() *ArtistTrackAnalytics {
	if x, ok := m.GetTrackAnalytics().(*UserGroupTrackAnalytics_ArtistTrackAnalytics); ok {
		return x.ArtistTrackAnalytics
	}
	return nil
}

func (m *UserGroupTrackAnalytics) GetLabelTrackAnalytics() *LabelTrackAnalytics {
	if x, ok := m.GetTrackAnalytics().(*UserGroupTrackAnalytics_LabelTrackAnalytics); ok {
		return x.LabelTrackAnalytics
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UserGroupTrackAnalytics) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UserGroupTrackAnalytics_OneofMarshaler, _UserGroupTrackAnalytics_OneofUnmarshaler, _UserGroupTrackAnalytics_OneofSizer, []interface{}{
		(*UserGroupTrackAnalytics_ArtistTrackAnalytics)(nil),
		(*UserGroupTrackAnalytics_LabelTrackAnalytics)(nil),
	}
}

func _UserGroupTrackAnalytics_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UserGroupTrackAnalytics)
	// track_analytics
	switch x := m.TrackAnalytics.(type) {
	case *UserGroupTrackAnalytics_ArtistTrackAnalytics:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ArtistTrackAnalytics); err != nil {
			return err
		}
	case *UserGroupTrackAnalytics_LabelTrackAnalytics:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LabelTrackAnalytics); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UserGroupTrackAnalytics.TrackAnalytics has unexpected type %T", x)
	}
	return nil
}

func _UserGroupTrackAnalytics_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UserGroupTrackAnalytics)
	switch tag {
	case 1: // track_analytics.artist_track_analytics
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ArtistTrackAnalytics)
		err := b.DecodeMessage(msg)
		m.TrackAnalytics = &UserGroupTrackAnalytics_ArtistTrackAnalytics{msg}
		return true, err
	case 2: // track_analytics.label_track_analytics
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LabelTrackAnalytics)
		err := b.DecodeMessage(msg)
		m.TrackAnalytics = &UserGroupTrackAnalytics_LabelTrackAnalytics{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UserGroupTrackAnalytics_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UserGroupTrackAnalytics)
	// track_analytics
	switch x := m.TrackAnalytics.(type) {
	case *UserGroupTrackAnalytics_ArtistTrackAnalytics:
		s := proto.Size(x.ArtistTrackAnalytics)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserGroupTrackAnalytics_LabelTrackAnalytics:
		s := proto.Size(x.LabelTrackAnalytics)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UserGroupRecommended struct {
	UserGroupId          string   `protobuf:"bytes,1,opt,name=user_group_id,json=userGroupId" json:"user_group_id,omitempty"`
	RecommendedId        string   `protobuf:"bytes,2,opt,name=recommended_id,json=recommendedId" json:"recommended_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGroupRecommended) Reset()         { *m = UserGroupRecommended{} }
func (m *UserGroupRecommended) String() string { return proto.CompactTextString(m) }
func (*UserGroupRecommended) ProtoMessage()    {}
func (*UserGroupRecommended) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{5}
}
func (m *UserGroupRecommended) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroupRecommended.Unmarshal(m, b)
}
func (m *UserGroupRecommended) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroupRecommended.Marshal(b, m, deterministic)
}
func (dst *UserGroupRecommended) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroupRecommended.Merge(dst, src)
}
func (m *UserGroupRecommended) XXX_Size() int {
	return xxx_messageInfo_UserGroupRecommended.Size(m)
}
func (m *UserGroupRecommended) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroupRecommended.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroupRecommended proto.InternalMessageInfo

func (m *UserGroupRecommended) GetUserGroupId() string {
	if m != nil {
		return m.UserGroupId
	}
	return ""
}

func (m *UserGroupRecommended) GetRecommendedId() string {
	if m != nil {
		return m.RecommendedId
	}
	return ""
}

type UserGroupMembers struct {
	UserGroupId          string       `protobuf:"bytes,1,opt,name=user_group_id,json=userGroupId" json:"user_group_id,omitempty"`
	Members              []*UserGroup `protobuf:"bytes,2,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserGroupMembers) Reset()         { *m = UserGroupMembers{} }
func (m *UserGroupMembers) String() string { return proto.CompactTextString(m) }
func (*UserGroupMembers) ProtoMessage()    {}
func (*UserGroupMembers) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{6}
}
func (m *UserGroupMembers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroupMembers.Unmarshal(m, b)
}
func (m *UserGroupMembers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroupMembers.Marshal(b, m, deterministic)
}
func (dst *UserGroupMembers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroupMembers.Merge(dst, src)
}
func (m *UserGroupMembers) XXX_Size() int {
	return xxx_messageInfo_UserGroupMembers.Size(m)
}
func (m *UserGroupMembers) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroupMembers.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroupMembers proto.InternalMessageInfo

func (m *UserGroupMembers) GetUserGroupId() string {
	if m != nil {
		return m.UserGroupId
	}
	return ""
}

func (m *UserGroupMembers) GetMembers() []*UserGroup {
	if m != nil {
		return m.Members
	}
	return nil
}

type GroupTaxonomy struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupTaxonomy) Reset()         { *m = GroupTaxonomy{} }
func (m *GroupTaxonomy) String() string { return proto.CompactTextString(m) }
func (*GroupTaxonomy) ProtoMessage()    {}
func (*GroupTaxonomy) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{7}
}
func (m *GroupTaxonomy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupTaxonomy.Unmarshal(m, b)
}
func (m *GroupTaxonomy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupTaxonomy.Marshal(b, m, deterministic)
}
func (dst *GroupTaxonomy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupTaxonomy.Merge(dst, src)
}
func (m *GroupTaxonomy) XXX_Size() int {
	return xxx_messageInfo_GroupTaxonomy.Size(m)
}
func (m *GroupTaxonomy) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupTaxonomy.DiscardUnknown(m)
}

var xxx_messageInfo_GroupTaxonomy proto.InternalMessageInfo

func (m *GroupTaxonomy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GroupTaxonomy) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GroupTaxonomy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GroupTaxonomies struct {
	Types                []*GroupTaxonomy `protobuf:"bytes,1,rep,name=types" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GroupTaxonomies) Reset()         { *m = GroupTaxonomies{} }
func (m *GroupTaxonomies) String() string { return proto.CompactTextString(m) }
func (*GroupTaxonomies) ProtoMessage()    {}
func (*GroupTaxonomies) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{8}
}
func (m *GroupTaxonomies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupTaxonomies.Unmarshal(m, b)
}
func (m *GroupTaxonomies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupTaxonomies.Marshal(b, m, deterministic)
}
func (dst *GroupTaxonomies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupTaxonomies.Merge(dst, src)
}
func (m *GroupTaxonomies) XXX_Size() int {
	return xxx_messageInfo_GroupTaxonomies.Size(m)
}
func (m *GroupTaxonomies) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupTaxonomies.DiscardUnknown(m)
}

var xxx_messageInfo_GroupTaxonomies proto.InternalMessageInfo

func (m *GroupTaxonomies) GetTypes() []*GroupTaxonomy {
	if m != nil {
		return m.Types
	}
	return nil
}

type Link struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=platform" json:"platform,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Uri                  string   `protobuf:"bytes,4,opt,name=uri" json:"uri,omitempty"`
	PersonalData         bool     `protobuf:"varint,5,opt,name=personal_data,json=personalData" json:"personal_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{9}
}
func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (dst *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(dst, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Link) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Link) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Link) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Link) GetPersonalData() bool {
	if m != nil {
		return m.PersonalData
	}
	return false
}

type Privacy struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Private              bool     `protobuf:"varint,2,opt,name=private" json:"private,omitempty"`
	OwnedTracks          bool     `protobuf:"varint,3,opt,name=owned_tracks,json=ownedTracks" json:"owned_tracks,omitempty"`
	SupportedArtists     bool     `protobuf:"varint,4,opt,name=supported_artists,json=supportedArtists" json:"supported_artists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Privacy) Reset()         { *m = Privacy{} }
func (m *Privacy) String() string { return proto.CompactTextString(m) }
func (*Privacy) ProtoMessage()    {}
func (*Privacy) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{10}
}
func (m *Privacy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Privacy.Unmarshal(m, b)
}
func (m *Privacy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Privacy.Marshal(b, m, deterministic)
}
func (dst *Privacy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Privacy.Merge(dst, src)
}
func (m *Privacy) XXX_Size() int {
	return xxx_messageInfo_Privacy.Size(m)
}
func (m *Privacy) XXX_DiscardUnknown() {
	xxx_messageInfo_Privacy.DiscardUnknown(m)
}

var xxx_messageInfo_Privacy proto.InternalMessageInfo

func (m *Privacy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Privacy) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *Privacy) GetOwnedTracks() bool {
	if m != nil {
		return m.OwnedTracks
	}
	return false
}

func (m *Privacy) GetSupportedArtists() bool {
	if m != nil {
		return m.SupportedArtists
	}
	return false
}

type GroupedUserGroups struct {
	Labels               []*UserGroup `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty"`
	Artists              []*UserGroup `protobuf:"bytes,2,rep,name=artists" json:"artists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupedUserGroups) Reset()         { *m = GroupedUserGroups{} }
func (m *GroupedUserGroups) String() string { return proto.CompactTextString(m) }
func (*GroupedUserGroups) ProtoMessage()    {}
func (*GroupedUserGroups) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_0139db6398cd59d5, []int{11}
}
func (m *GroupedUserGroups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupedUserGroups.Unmarshal(m, b)
}
func (m *GroupedUserGroups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupedUserGroups.Marshal(b, m, deterministic)
}
func (dst *GroupedUserGroups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupedUserGroups.Merge(dst, src)
}
func (m *GroupedUserGroups) XXX_Size() int {
	return xxx_messageInfo_GroupedUserGroups.Size(m)
}
func (m *GroupedUserGroups) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupedUserGroups.DiscardUnknown(m)
}

var xxx_messageInfo_GroupedUserGroups proto.InternalMessageInfo

func (m *GroupedUserGroups) GetLabels() []*UserGroup {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *GroupedUserGroups) GetArtists() []*UserGroup {
	if m != nil {
		return m.Artists
	}
	return nil
}

func init() {
	proto.RegisterType((*UserGroup)(nil), "resonate.api.user.UserGroup")
	proto.RegisterType((*TrackAnalytics)(nil), "resonate.api.user.TrackAnalytics")
	proto.RegisterType((*ArtistTrackAnalytics)(nil), "resonate.api.user.ArtistTrackAnalytics")
	proto.RegisterType((*LabelTrackAnalytics)(nil), "resonate.api.user.LabelTrackAnalytics")
	proto.RegisterType((*LabelTrackAnalytics_ArtistTrackAnalytics)(nil), "resonate.api.user.LabelTrackAnalytics.ArtistTrackAnalytics")
	proto.RegisterType((*UserGroupTrackAnalytics)(nil), "resonate.api.user.UserGroupTrackAnalytics")
	proto.RegisterType((*UserGroupRecommended)(nil), "resonate.api.user.UserGroupRecommended")
	proto.RegisterType((*UserGroupMembers)(nil), "resonate.api.user.UserGroupMembers")
	proto.RegisterType((*GroupTaxonomy)(nil), "resonate.api.user.GroupTaxonomy")
	proto.RegisterType((*GroupTaxonomies)(nil), "resonate.api.user.GroupTaxonomies")
	proto.RegisterType((*Link)(nil), "resonate.api.user.Link")
	proto.RegisterType((*Privacy)(nil), "resonate.api.user.Privacy")
	proto.RegisterType((*GroupedUserGroups)(nil), "resonate.api.user.GroupedUserGroups")
}

func init() {
	proto.RegisterFile("rpc/usergroup/service.proto", fileDescriptor_service_0139db6398cd59d5)
}

var fileDescriptor_service_0139db6398cd59d5 = []byte{
	// 1193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5b, 0x6f, 0x1b, 0xc5,
	0x17, 0xaf, 0x1d, 0x5f, 0x8f, 0x2f, 0xb1, 0x27, 0xfe, 0xa7, 0xfb, 0x77, 0x41, 0x75, 0xb7, 0x85,
	0x86, 0x42, 0x5d, 0x29, 0x14, 0x24, 0xe8, 0x53, 0xda, 0x54, 0x6e, 0xa0, 0x2d, 0xed, 0xc6, 0xe9,
	0x03, 0x02, 0x59, 0x13, 0xcf, 0x24, 0x19, 0x65, 0xbd, 0xbb, 0x9a, 0x19, 0xa7, 0xf8, 0x81, 0x07,
	0xc4, 0x3b, 0x2f, 0x88, 0x4f, 0xc9, 0x0b, 0x5f, 0x00, 0x09, 0xcd, 0x65, 0xd7, 0x1b, 0xdf, 0xea,
	0x48, 0x79, 0xb1, 0x76, 0xce, 0xf9, 0x9d, 0xdf, 0x9c, 0x39, 0x97, 0x39, 0x63, 0xb8, 0xc5, 0xa3,
	0xe1, 0xa3, 0xb1, 0xa0, 0xfc, 0x94, 0x87, 0xe3, 0xe8, 0x91, 0xa0, 0xfc, 0x82, 0x0d, 0x69, 0x37,
	0xe2, 0xa1, 0x0c, 0x51, 0x93, 0x53, 0x11, 0x06, 0x58, 0xd2, 0x2e, 0x8e, 0x58, 0x57, 0xa1, 0xda,
	0xb7, 0xd5, 0xef, 0x43, 0x1c, 0xb1, 0x47, 0xb1, 0xe1, 0x65, 0x9b, 0x76, 0xe7, 0x12, 0x40, 0x72,
	0x3c, 0x3c, 0xbf, 0x8c, 0x70, 0xff, 0x29, 0x42, 0xf9, 0x48, 0x50, 0xde, 0x53, 0x3b, 0xa2, 0x3a,
	0x64, 0x19, 0x71, 0x32, 0x9d, 0xcc, 0x4e, 0xd9, 0xcb, 0x32, 0x82, 0xee, 0x40, 0x95, 0x30, 0x11,
	0xf9, 0x78, 0x32, 0x08, 0xf0, 0x88, 0x3a, 0x59, 0xad, 0xa9, 0x58, 0xd9, 0x6b, 0x3c, 0xa2, 0xa8,
	0x03, 0x15, 0x42, 0xc5, 0x90, 0xb3, 0x48, 0xb2, 0x30, 0x70, 0x36, 0x2c, 0x62, 0x2a, 0x42, 0xb7,
	0xa0, 0x2c, 0xce, 0x42, 0x2e, 0x07, 0xc7, 0x2c, 0x74, 0x72, 0x5a, 0x5f, 0xd2, 0x82, 0xa7, 0x2c,
	0x44, 0xdb, 0x50, 0xc0, 0x17, 0x58, 0x62, 0xee, 0xe4, 0x3b, 0x99, 0x9d, 0xaa, 0x67, 0x57, 0x4a,
	0x7e, 0x8c, 0x83, 0x80, 0x72, 0xa7, 0x60, 0xe4, 0x66, 0x85, 0xfe, 0x0f, 0xa5, 0xf0, 0x7d, 0x40,
	0xf9, 0x80, 0x11, 0xa7, 0xa8, 0xb9, 0x8a, 0x7a, 0x7d, 0x40, 0xd0, 0x63, 0xc8, 0xc9, 0x49, 0x44,
	0x9d, 0x52, 0x27, 0xb3, 0x53, 0xd9, 0xed, 0x74, 0xe7, 0xe2, 0xd5, 0xd5, 0x87, 0xec, 0xe3, 0x5f,
	0xc2, 0x20, 0x1c, 0x4d, 0x3c, 0x8d, 0x46, 0x5f, 0x41, 0xf9, 0x24, 0xf4, 0xfd, 0xf0, 0x3d, 0xe5,
	0xc2, 0x29, 0x77, 0x36, 0x76, 0x2a, 0xbb, 0x37, 0x17, 0x98, 0xaa, 0x18, 0x79, 0x53, 0x24, 0xfa,
	0x1a, 0x8a, 0x23, 0x3a, 0x3a, 0x56, 0x46, 0xa0, 0x8d, 0x3e, 0x5a, 0x62, 0xa4, 0xf7, 0xf4, 0x62,
	0x30, 0xda, 0x87, 0xba, 0xf9, 0xfc, 0xe1, 0x44, 0x6b, 0x84, 0x53, 0x59, 0xc3, 0x7c, 0xc6, 0x06,
	0x3d, 0x84, 0xbc, 0xcf, 0x82, 0x73, 0xe1, 0x54, 0x97, 0x3a, 0xfc, 0x92, 0x05, 0xe7, 0x9e, 0x41,
	0xa1, 0x07, 0x90, 0x93, 0xf8, 0x54, 0x38, 0x35, 0x8d, 0xde, 0x5e, 0x80, 0xee, 0xe3, 0x53, 0x4f,
	0x63, 0xd0, 0xb7, 0x50, 0xc4, 0x84, 0x70, 0x2a, 0x84, 0x53, 0x5f, 0x1a, 0xc8, 0x43, 0xc9, 0x29,
	0x95, 0x7b, 0x06, 0xe7, 0xc5, 0x06, 0xe8, 0x31, 0x14, 0x23, 0xce, 0x2e, 0xf0, 0x70, 0xe2, 0x34,
	0xb4, 0x6d, 0x7b, 0x81, 0xed, 0x1b, 0x83, 0xf0, 0x62, 0x28, 0xea, 0xc3, 0x16, 0xa7, 0xc3, 0x70,
	0x34, 0xa2, 0x01, 0xa1, 0x64, 0x80, 0xb9, 0x64, 0x42, 0x0a, 0xa7, 0xa9, 0x9d, 0xbd, 0xbb, 0x80,
	0xc1, 0xa3, 0x3e, 0x96, 0x94, 0x4c, 0xc3, 0x83, 0x52, 0xf6, 0x7b, 0xc6, 0x1c, 0xbd, 0x83, 0xd6,
	0x09, 0xc5, 0x72, 0xcc, 0x29, 0x19, 0xe8, 0xc2, 0x1f, 0xe8, 0xa6, 0x72, 0x90, 0x76, 0xec, 0xde,
	0x72, 0xda, 0xbe, 0x02, 0x5b, 0xde, 0x98, 0x61, 0x2a, 0x43, 0x3d, 0xa8, 0xa6, 0xe8, 0x84, 0xb3,
	0xa5, 0xdd, 0x5c, 0x8f, 0xaf, 0x22, 0x93, 0x6f, 0x81, 0x7a, 0x80, 0xce, 0xd8, 0xe9, 0x99, 0xcf,
	0x4e, 0xcf, 0x64, 0xec, 0xa3, 0x70, 0x5a, 0x9a, 0xce, 0x59, 0x94, 0x22, 0x05, 0xf0, 0x9a, 0x29,
	0x1b, 0x2d, 0x11, 0xa8, 0x0b, 0x5b, 0xda, 0x97, 0x01, 0x1d, 0x61, 0xe6, 0x0f, 0xe2, 0xec, 0x6d,
	0xeb, 0xee, 0x68, 0x6a, 0xd5, 0x73, 0xa5, 0xb1, 0xe9, 0x72, 0xff, 0xcc, 0x42, 0x5d, 0x9b, 0xee,
	0x05, 0xd8, 0x9f, 0x48, 0x36, 0x14, 0x73, 0x7d, 0xdf, 0x82, 0xbc, 0x64, 0xd2, 0x8f, 0x1b, 0xde,
	0x2c, 0xd0, 0x6d, 0xa8, 0xc8, 0x50, 0x62, 0x7f, 0xa0, 0x9a, 0x5f, 0xe8, 0x56, 0xcf, 0x7b, 0xa0,
	0x45, 0x6f, 0x94, 0x04, 0x7d, 0x0c, 0x10, 0x61, 0x46, 0xac, 0x3e, 0xa7, 0xf5, 0x65, 0x25, 0x49,
	0xd4, 0x27, 0x9c, 0x52, 0xab, 0xce, 0x1b, 0xb5, 0x92, 0x18, 0xf5, 0x5d, 0xa8, 0x19, 0xfa, 0x21,
	0xa7, 0x84, 0x49, 0xa1, 0x3b, 0x3f, 0xeb, 0x55, 0xb5, 0xf0, 0x99, 0x91, 0xa1, 0x2f, 0x00, 0xa9,
	0x68, 0x98, 0xe8, 0x27, 0xc8, 0xa2, 0x46, 0x36, 0xc6, 0x71, 0x45, 0xc4, 0xe8, 0xcf, 0xa0, 0x11,
	0x07, 0x32, 0xc1, 0x96, 0x34, 0x76, 0x33, 0x96, 0x5b, 0xa8, 0xfb, 0x16, 0x5a, 0xa6, 0x74, 0x66,
	0x42, 0xf3, 0x0d, 0x14, 0x6c, 0x6a, 0x32, 0x3a, 0x35, 0x77, 0x96, 0xa5, 0x26, 0x31, 0xf1, 0xac,
	0x81, 0xfb, 0x6f, 0x06, 0xb6, 0x5e, 0xe2, 0x63, 0xea, 0xcf, 0x50, 0x1e, 0x41, 0x31, 0x2e, 0x72,
	0xc3, 0xf9, 0x64, 0x51, 0xff, 0xce, 0x1b, 0x76, 0x17, 0x39, 0xe8, 0xc5, 0x5c, 0xed, 0x3f, 0x32,
	0x4b, 0x8e, 0xf0, 0x04, 0x0a, 0x06, 0xa3, 0x33, 0xbc, 0x66, 0x4f, 0x59, 0x93, 0xd4, 0xf9, 0xb3,
	0x57, 0x3d, 0xff, 0xdf, 0x19, 0xb8, 0x99, 0x10, 0xce, 0xf8, 0x34, 0x80, 0x6d, 0xb3, 0x81, 0x6d,
	0x4e, 0x1c, 0x6b, 0xac, 0x8f, 0xf7, 0x17, 0x6c, 0xb3, 0xe8, 0x70, 0x2f, 0x6e, 0x78, 0x2d, 0xbc,
	0xe8, 0xd0, 0x3f, 0xc1, 0xff, 0x7c, 0x15, 0xc2, 0x39, 0xfe, 0xac, 0xe6, 0xff, 0x74, 0xbd, 0x90,
	0xbf, 0xb8, 0xe1, 0x6d, 0xf9, 0xf3, 0xe2, 0xa7, 0x4d, 0xd8, 0x9c, 0xe1, 0x75, 0x31, 0xb4, 0xa6,
	0xd1, 0x9b, 0xde, 0x47, 0xc8, 0x85, 0x5a, 0xaa, 0x62, 0x93, 0x36, 0xab, 0x24, 0xc5, 0x7a, 0x40,
	0xd0, 0x27, 0x50, 0x4f, 0x5f, 0x81, 0x8c, 0xd8, 0xc6, 0xab, 0xa5, 0xa4, 0x07, 0xc4, 0x0d, 0xa0,
	0x91, 0x6c, 0xf1, 0xca, 0x0e, 0x94, 0x75, 0xe8, 0x53, 0xc3, 0x2a, 0x7b, 0x85, 0x61, 0xe5, 0xf6,
	0xa0, 0x76, 0x69, 0x64, 0xce, 0xdd, 0x13, 0xc8, 0x8e, 0x5c, 0xe3, 0xad, 0x19, 0xa8, 0x08, 0x72,
	0xfa, 0xad, 0x60, 0x5e, 0x02, 0xfa, 0xdb, 0x3d, 0x80, 0xcd, 0x34, 0x11, 0xa3, 0x6a, 0x80, 0xe6,
	0x15, 0x3c, 0x6e, 0x81, 0x0f, 0x8f, 0x6b, 0x03, 0x77, 0x7f, 0x85, 0x9c, 0x1a, 0x6d, 0x73, 0xae,
	0xb4, 0xa1, 0x14, 0xf9, 0x58, 0x9e, 0x84, 0x7c, 0x64, 0xdd, 0x49, 0xd6, 0x89, 0x9b, 0x1b, 0x29,
	0x37, 0x1b, 0xb0, 0x31, 0xe6, 0xcc, 0xbe, 0x47, 0xd4, 0xa7, 0xba, 0x7f, 0x22, 0xca, 0x95, 0x13,
	0xfe, 0x80, 0x60, 0x89, 0xf5, 0x0d, 0x55, 0xf2, 0xaa, 0xb1, 0x70, 0x1f, 0x4b, 0xec, 0xfe, 0x9e,
	0x81, 0xa2, 0x9d, 0x60, 0x73, 0x2e, 0x38, 0x76, 0xfc, 0x49, 0x13, 0x90, 0x92, 0x17, 0x2f, 0xd5,
	0x3b, 0x4a, 0xbd, 0x52, 0x92, 0x5b, 0x7e, 0x43, 0xab, 0x2b, 0x5a, 0x66, 0x6f, 0xf1, 0xcf, 0xa1,
	0x29, 0xc6, 0x51, 0x14, 0x72, 0x99, 0x9a, 0x81, 0x39, 0x8d, 0x6b, 0x24, 0x0a, 0x3b, 0xdc, 0xdc,
	0xdf, 0x32, 0xd0, 0xd4, 0xd1, 0x49, 0x75, 0xac, 0x1a, 0xbf, 0x05, 0x5d, 0xab, 0x71, 0x4c, 0x57,
	0x67, 0xd9, 0x62, 0x55, 0x71, 0xc4, 0xdb, 0xad, 0x55, 0x1c, 0x16, 0xbc, 0xfb, 0x57, 0x31, 0x55,
	0x8d, 0x87, 0xe6, 0x51, 0x89, 0x5e, 0xc1, 0xe6, 0x33, 0x4e, 0xb1, 0xa4, 0xd3, 0x37, 0xe5, 0x4a,
	0xba, 0xf6, 0x4a, 0x2d, 0xfa, 0x0e, 0xaa, 0x3d, 0x2a, 0xaf, 0x87, 0xeb, 0x00, 0x36, 0x8f, 0x22,
	0x72, 0x05, 0xd7, 0x16, 0x0d, 0xe1, 0xe7, 0xa3, 0x48, 0x4e, 0x14, 0xd5, 0x3e, 0xf5, 0xe9, 0x75,
	0x50, 0xf5, 0x01, 0xf5, 0xa8, 0xd4, 0x37, 0x4f, 0x2a, 0x93, 0x4b, 0xf1, 0xed, 0x7b, 0xcb, 0xfa,
	0xe4, 0x52, 0x25, 0xbc, 0x85, 0x66, 0x3a, 0x6e, 0x7d, 0xd5, 0x39, 0x2b, 0x48, 0xdd, 0x0f, 0x34,
	0x9f, 0xea, 0xd7, 0x43, 0xa8, 0xef, 0x11, 0x92, 0xbe, 0xd8, 0xee, 0xaf, 0xac, 0x93, 0x29, 0x70,
	0xc5, 0xe9, 0xdf, 0x41, 0xd3, 0xa3, 0xa3, 0xf0, 0x82, 0x5e, 0x33, 0xef, 0xf7, 0x00, 0x7b, 0x84,
	0xc4, 0x57, 0xe4, 0xdd, 0x55, 0x84, 0x16, 0xb4, 0x82, 0xec, 0x35, 0xd4, 0x4c, 0xb6, 0xaf, 0x89,
	0xef, 0x67, 0x9d, 0x9c, 0x99, 0x71, 0xb5, 0xba, 0x7e, 0x1e, 0xac, 0xd2, 0xce, 0x8c, 0xa6, 0xca,
	0x8f, 0xe5, 0xe4, 0x2f, 0xe4, 0x71, 0x41, 0xff, 0xcb, 0xfb, 0xf2, 0xbf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x2d, 0x20, 0xe3, 0x59, 0x5a, 0x0e, 0x00, 0x00,
}
