// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/user/service.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tag "user-api/rpc/tag"
import track "user-api/rpc/track"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                     string                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username               string                  `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email                  string                  `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	DisplayName            string                  `protobuf:"bytes,4,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	FullName               string                  `protobuf:"bytes,5,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	FirstName              string                  `protobuf:"bytes,6,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName               string                  `protobuf:"bytes,7,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Member                 bool                    `protobuf:"varint,8,opt,name=member" json:"member,omitempty"`
	Avatar                 []byte                  `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	NewsletterNotification bool                    `protobuf:"varint,10,opt,name=newsletter_notification,json=newsletterNotification" json:"newsletter_notification,omitempty"`
	FavoriteTracks         []string                `protobuf:"bytes,11,rep,name=favorite_tracks,json=favoriteTracks" json:"favorite_tracks,omitempty"`
	FollowedGroups         []string                `protobuf:"bytes,12,rep,name=followed_groups,json=followedGroups" json:"followed_groups,omitempty"`
	OwnerOfGroups          []*tag.RelatedUserGroup `protobuf:"bytes,13,rep,name=owner_of_groups,json=ownerOfGroups" json:"owner_of_groups,omitempty"`
	ResidenceAddress       *StreetAddress          `protobuf:"bytes,14,opt,name=residence_address,json=residenceAddress" json:"residence_address,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8c05f99b118ee628, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetMember() bool {
	if m != nil {
		return m.Member
	}
	return false
}

func (m *User) GetAvatar() []byte {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *User) GetNewsletterNotification() bool {
	if m != nil {
		return m.NewsletterNotification
	}
	return false
}

func (m *User) GetFavoriteTracks() []string {
	if m != nil {
		return m.FavoriteTracks
	}
	return nil
}

func (m *User) GetFollowedGroups() []string {
	if m != nil {
		return m.FollowedGroups
	}
	return nil
}

func (m *User) GetOwnerOfGroups() []*tag.RelatedUserGroup {
	if m != nil {
		return m.OwnerOfGroups
	}
	return nil
}

func (m *User) GetResidenceAddress() *StreetAddress {
	if m != nil {
		return m.ResidenceAddress
	}
	return nil
}

type Playlists struct {
	Playlists            []*track.RelatedTrackGroup `protobuf:"bytes,1,rep,name=playlists" json:"playlists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Playlists) Reset()         { *m = Playlists{} }
func (m *Playlists) String() string { return proto.CompactTextString(m) }
func (*Playlists) ProtoMessage()    {}
func (*Playlists) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8c05f99b118ee628, []int{1}
}
func (m *Playlists) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Playlists.Unmarshal(m, b)
}
func (m *Playlists) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Playlists.Marshal(b, m, deterministic)
}
func (dst *Playlists) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Playlists.Merge(dst, src)
}
func (m *Playlists) XXX_Size() int {
	return xxx_messageInfo_Playlists.Size(m)
}
func (m *Playlists) XXX_DiscardUnknown() {
	xxx_messageInfo_Playlists.DiscardUnknown(m)
}

var xxx_messageInfo_Playlists proto.InternalMessageInfo

func (m *Playlists) GetPlaylists() []*track.RelatedTrackGroup {
	if m != nil {
		return m.Playlists
	}
	return nil
}

type Tracks struct {
	Tracks               []*track.Track `protobuf:"bytes,1,rep,name=tracks" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Tracks) Reset()         { *m = Tracks{} }
func (m *Tracks) String() string { return proto.CompactTextString(m) }
func (*Tracks) ProtoMessage()    {}
func (*Tracks) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8c05f99b118ee628, []int{2}
}
func (m *Tracks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracks.Unmarshal(m, b)
}
func (m *Tracks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracks.Marshal(b, m, deterministic)
}
func (dst *Tracks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracks.Merge(dst, src)
}
func (m *Tracks) XXX_Size() int {
	return xxx_messageInfo_Tracks.Size(m)
}
func (m *Tracks) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracks.DiscardUnknown(m)
}

var xxx_messageInfo_Tracks proto.InternalMessageInfo

func (m *Tracks) GetTracks() []*track.Track {
	if m != nil {
		return m.Tracks
	}
	return nil
}

type StreetAddress struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PersonalData         bool              `protobuf:"varint,3,opt,name=personal_data,json=personalData" json:"personal_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StreetAddress) Reset()         { *m = StreetAddress{} }
func (m *StreetAddress) String() string { return proto.CompactTextString(m) }
func (*StreetAddress) ProtoMessage()    {}
func (*StreetAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8c05f99b118ee628, []int{3}
}
func (m *StreetAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreetAddress.Unmarshal(m, b)
}
func (m *StreetAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreetAddress.Marshal(b, m, deterministic)
}
func (dst *StreetAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreetAddress.Merge(dst, src)
}
func (m *StreetAddress) XXX_Size() int {
	return xxx_messageInfo_StreetAddress.Size(m)
}
func (m *StreetAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_StreetAddress.DiscardUnknown(m)
}

var xxx_messageInfo_StreetAddress proto.InternalMessageInfo

func (m *StreetAddress) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreetAddress) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StreetAddress) GetPersonalData() bool {
	if m != nil {
		return m.PersonalData
	}
	return false
}

type Artists struct {
	Artists              []*tag.RelatedUserGroup `protobuf:"bytes,1,rep,name=artists" json:"artists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Artists) Reset()         { *m = Artists{} }
func (m *Artists) String() string { return proto.CompactTextString(m) }
func (*Artists) ProtoMessage()    {}
func (*Artists) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8c05f99b118ee628, []int{4}
}
func (m *Artists) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Artists.Unmarshal(m, b)
}
func (m *Artists) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Artists.Marshal(b, m, deterministic)
}
func (dst *Artists) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Artists.Merge(dst, src)
}
func (m *Artists) XXX_Size() int {
	return xxx_messageInfo_Artists.Size(m)
}
func (m *Artists) XXX_DiscardUnknown() {
	xxx_messageInfo_Artists.DiscardUnknown(m)
}

var xxx_messageInfo_Artists proto.InternalMessageInfo

func (m *Artists) GetArtists() []*tag.RelatedUserGroup {
	if m != nil {
		return m.Artists
	}
	return nil
}

// Used for:
// - following/unfollowing group
type UserToUserGroup struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserGroupId          string   `protobuf:"bytes,2,opt,name=user_group_id,json=userGroupId" json:"user_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserToUserGroup) Reset()         { *m = UserToUserGroup{} }
func (m *UserToUserGroup) String() string { return proto.CompactTextString(m) }
func (*UserToUserGroup) ProtoMessage()    {}
func (*UserToUserGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8c05f99b118ee628, []int{5}
}
func (m *UserToUserGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToUserGroup.Unmarshal(m, b)
}
func (m *UserToUserGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToUserGroup.Marshal(b, m, deterministic)
}
func (dst *UserToUserGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToUserGroup.Merge(dst, src)
}
func (m *UserToUserGroup) XXX_Size() int {
	return xxx_messageInfo_UserToUserGroup.Size(m)
}
func (m *UserToUserGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToUserGroup.DiscardUnknown(m)
}

var xxx_messageInfo_UserToUserGroup proto.InternalMessageInfo

func (m *UserToUserGroup) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserToUserGroup) GetUserGroupId() string {
	if m != nil {
		return m.UserGroupId
	}
	return ""
}

// Used for:
// - adding/removing favorite tracks
type UserToTrack struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	TrackId              string   `protobuf:"bytes,2,opt,name=track_id,json=trackId" json:"track_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserToTrack) Reset()         { *m = UserToTrack{} }
func (m *UserToTrack) String() string { return proto.CompactTextString(m) }
func (*UserToTrack) ProtoMessage()    {}
func (*UserToTrack) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8c05f99b118ee628, []int{6}
}
func (m *UserToTrack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToTrack.Unmarshal(m, b)
}
func (m *UserToTrack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToTrack.Marshal(b, m, deterministic)
}
func (dst *UserToTrack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToTrack.Merge(dst, src)
}
func (m *UserToTrack) XXX_Size() int {
	return xxx_messageInfo_UserToTrack.Size(m)
}
func (m *UserToTrack) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToTrack.DiscardUnknown(m)
}

var xxx_messageInfo_UserToTrack proto.InternalMessageInfo

func (m *UserToTrack) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserToTrack) GetTrackId() string {
	if m != nil {
		return m.TrackId
	}
	return ""
}

// Used for:
// - adding a track play (i.e. track has been streamed >=45s)
type Play struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	TrackId              string   `protobuf:"bytes,2,opt,name=track_id,json=trackId" json:"track_id,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Credits              float32  `protobuf:"fixed32,4,opt,name=credits" json:"credits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Play) Reset()         { *m = Play{} }
func (m *Play) String() string { return proto.CompactTextString(m) }
func (*Play) ProtoMessage()    {}
func (*Play) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8c05f99b118ee628, []int{7}
}
func (m *Play) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Play.Unmarshal(m, b)
}
func (m *Play) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Play.Marshal(b, m, deterministic)
}
func (dst *Play) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Play.Merge(dst, src)
}
func (m *Play) XXX_Size() int {
	return xxx_messageInfo_Play.Size(m)
}
func (m *Play) XXX_DiscardUnknown() {
	xxx_messageInfo_Play.DiscardUnknown(m)
}

var xxx_messageInfo_Play proto.InternalMessageInfo

func (m *Play) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Play) GetTrackId() string {
	if m != nil {
		return m.TrackId
	}
	return ""
}

func (m *Play) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Play) GetCredits() float32 {
	if m != nil {
		return m.Credits
	}
	return 0
}

type CreatePlayRequest struct {
	Play                 *Play    `protobuf:"bytes,1,opt,name=play" json:"play,omitempty"`
	UpdatedCredits       float32  `protobuf:"fixed32,2,opt,name=updated_credits,json=updatedCredits" json:"updated_credits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlayRequest) Reset()         { *m = CreatePlayRequest{} }
func (m *CreatePlayRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlayRequest) ProtoMessage()    {}
func (*CreatePlayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8c05f99b118ee628, []int{8}
}
func (m *CreatePlayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayRequest.Unmarshal(m, b)
}
func (m *CreatePlayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePlayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayRequest.Merge(dst, src)
}
func (m *CreatePlayRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlayRequest.Size(m)
}
func (m *CreatePlayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayRequest proto.InternalMessageInfo

func (m *CreatePlayRequest) GetPlay() *Play {
	if m != nil {
		return m.Play
	}
	return nil
}

func (m *CreatePlayRequest) GetUpdatedCredits() float32 {
	if m != nil {
		return m.UpdatedCredits
	}
	return 0
}

type CreatePlayResponse struct {
	UpdatedPlayCount     int32    `protobuf:"varint,1,opt,name=updated_play_count,json=updatedPlayCount" json:"updated_play_count,omitempty"`
	UpdatedCredits       float32  `protobuf:"fixed32,2,opt,name=updated_credits,json=updatedCredits" json:"updated_credits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlayResponse) Reset()         { *m = CreatePlayResponse{} }
func (m *CreatePlayResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePlayResponse) ProtoMessage()    {}
func (*CreatePlayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_8c05f99b118ee628, []int{9}
}
func (m *CreatePlayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayResponse.Unmarshal(m, b)
}
func (m *CreatePlayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayResponse.Marshal(b, m, deterministic)
}
func (dst *CreatePlayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayResponse.Merge(dst, src)
}
func (m *CreatePlayResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePlayResponse.Size(m)
}
func (m *CreatePlayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayResponse proto.InternalMessageInfo

func (m *CreatePlayResponse) GetUpdatedPlayCount() int32 {
	if m != nil {
		return m.UpdatedPlayCount
	}
	return 0
}

func (m *CreatePlayResponse) GetUpdatedCredits() float32 {
	if m != nil {
		return m.UpdatedCredits
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "resonate.api.user.User")
	proto.RegisterType((*Playlists)(nil), "resonate.api.user.Playlists")
	proto.RegisterType((*Tracks)(nil), "resonate.api.user.Tracks")
	proto.RegisterType((*StreetAddress)(nil), "resonate.api.user.StreetAddress")
	proto.RegisterMapType((map[string]string)(nil), "resonate.api.user.StreetAddress.DataEntry")
	proto.RegisterType((*Artists)(nil), "resonate.api.user.Artists")
	proto.RegisterType((*UserToUserGroup)(nil), "resonate.api.user.UserToUserGroup")
	proto.RegisterType((*UserToTrack)(nil), "resonate.api.user.UserToTrack")
	proto.RegisterType((*Play)(nil), "resonate.api.user.Play")
	proto.RegisterType((*CreatePlayRequest)(nil), "resonate.api.user.CreatePlayRequest")
	proto.RegisterType((*CreatePlayResponse)(nil), "resonate.api.user.CreatePlayResponse")
}

func init() { proto.RegisterFile("rpc/user/service.proto", fileDescriptor_service_8c05f99b118ee628) }

var fileDescriptor_service_8c05f99b118ee628 = []byte{
	// 918 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x85, 0x2e, 0xd6, 0x65, 0x74, 0xb1, 0xbd, 0x29, 0x6c, 0x46, 0x6d, 0x03, 0x95, 0x69, 0x51,
	0xa1, 0x17, 0xb9, 0x70, 0x1f, 0x52, 0xa4, 0x68, 0x0a, 0xc7, 0x17, 0xc5, 0x4d, 0x63, 0x17, 0x74,
	0xfc, 0xd0, 0xbe, 0x10, 0x1b, 0x71, 0x94, 0x12, 0xa6, 0x48, 0x76, 0x77, 0x29, 0x43, 0xdf, 0xd0,
	0x4f, 0xe8, 0xb7, 0xf4, 0xdf, 0x82, 0x9d, 0x5d, 0xca, 0x16, 0x2c, 0x3a, 0x81, 0x90, 0x17, 0x81,
	0x73, 0xce, 0x9c, 0x33, 0xcb, 0xd9, 0xdd, 0xa1, 0x60, 0x47, 0xa4, 0xe3, 0xbd, 0x4c, 0xa2, 0xd8,
	0x93, 0x28, 0x66, 0xe1, 0x18, 0x87, 0xa9, 0x48, 0x54, 0xc2, 0xb6, 0x05, 0xca, 0x24, 0xe6, 0x0a,
	0x87, 0x3c, 0x0d, 0x87, 0x3a, 0xa1, 0xd7, 0xd7, 0xbf, 0xdf, 0xf3, 0x34, 0xdc, 0xd3, 0x1a, 0x25,
	0xf8, 0xf8, 0x6a, 0x59, 0xd4, 0x7b, 0xb4, 0x9c, 0xc1, 0xdf, 0x2e, 0xf3, 0xee, 0x7f, 0x55, 0xa8,
	0x5e, 0x4a, 0x14, 0xac, 0x0b, 0xe5, 0x30, 0x70, 0x4a, 0xfd, 0xd2, 0xa0, 0xe9, 0x95, 0xc3, 0x80,
	0xf5, 0xa0, 0xa1, 0xa5, 0x31, 0x9f, 0xa2, 0x53, 0x26, 0x74, 0x11, 0xb3, 0x4f, 0x60, 0x03, 0xa7,
	0x3c, 0x8c, 0x9c, 0x0a, 0x11, 0x26, 0x60, 0x5f, 0x40, 0x3b, 0x08, 0x65, 0x1a, 0xf1, 0xb9, 0x4f,
	0xaa, 0x2a, 0x91, 0x2d, 0x8b, 0x9d, 0x69, 0xe1, 0xa7, 0xd0, 0x9c, 0x64, 0x51, 0x64, 0xf8, 0x0d,
	0xe3, 0xaa, 0x01, 0x22, 0x3f, 0x07, 0x98, 0x84, 0x42, 0x2a, 0xc3, 0xd6, 0x88, 0x6d, 0x12, 0x92,
	0x6b, 0x23, 0x9e, 0xb3, 0x75, 0xa3, 0xd5, 0x00, 0x91, 0x3b, 0x50, 0x9b, 0xe2, 0xf4, 0x0d, 0x0a,
	0xa7, 0xd1, 0x2f, 0x0d, 0x1a, 0x9e, 0x8d, 0x34, 0xce, 0x67, 0x5c, 0x71, 0xe1, 0x34, 0xfb, 0xa5,
	0x41, 0xdb, 0xb3, 0x11, 0x7b, 0x02, 0xbb, 0x31, 0x5e, 0xcb, 0x08, 0x95, 0x42, 0xe1, 0xc7, 0x89,
	0x0a, 0x27, 0xe1, 0x98, 0xab, 0x30, 0x89, 0x1d, 0x20, 0x83, 0x9d, 0x1b, 0xfa, 0xec, 0x16, 0xcb,
	0xbe, 0x86, 0xcd, 0x09, 0x9f, 0x25, 0x22, 0x54, 0xe8, 0x53, 0xbf, 0xa5, 0xd3, 0xea, 0x57, 0x06,
	0x4d, 0xaf, 0x9b, 0xc3, 0xaf, 0x09, 0xa5, 0xc4, 0x24, 0x8a, 0x92, 0x6b, 0x0c, 0xfc, 0xb7, 0x22,
	0xc9, 0x52, 0xe9, 0xb4, 0x6d, 0xa2, 0x85, 0x47, 0x84, 0xb2, 0x97, 0xb0, 0x99, 0x5c, 0xc7, 0x28,
	0xfc, 0x64, 0x92, 0x27, 0x76, 0xfa, 0x95, 0x41, 0x6b, 0xff, 0xf1, 0xf0, 0xce, 0x86, 0x0f, 0x3d,
	0x8c, 0xb8, 0xc2, 0x40, 0xef, 0x18, 0xc9, 0xbd, 0x0e, 0x69, 0xcf, 0x27, 0xd6, 0xec, 0x15, 0xe8,
	0x53, 0x12, 0x06, 0x18, 0x8f, 0xd1, 0xe7, 0x41, 0x20, 0x50, 0x4a, 0xa7, 0xdb, 0x2f, 0x0d, 0x5a,
	0xfb, 0xfd, 0x15, 0x76, 0x17, 0x4a, 0x20, 0xaa, 0x03, 0x93, 0xe7, 0x6d, 0x2d, 0xa4, 0x16, 0x71,
	0xcf, 0xa1, 0xf9, 0x47, 0xc4, 0xe7, 0x51, 0x28, 0x95, 0x64, 0xcf, 0xa1, 0x99, 0xe6, 0x81, 0x53,
	0xa2, 0x25, 0x7e, 0x59, 0xbc, 0x44, 0x6a, 0x83, 0x59, 0xe3, 0x8d, 0xcc, 0x7d, 0x0a, 0x35, 0xdb,
	0x9f, 0x1f, 0xa0, 0x66, 0xfb, 0x67, 0xac, 0x9c, 0x15, 0x56, 0x94, 0xea, 0xd9, 0x3c, 0xf7, 0xff,
	0x12, 0x74, 0x96, 0x16, 0x7c, 0xe7, 0xcc, 0x3e, 0x83, 0x6a, 0xc0, 0x15, 0x77, 0xca, 0xe4, 0xf8,
	0xcd, 0xfb, 0x5e, 0x78, 0x78, 0xc4, 0x15, 0x3f, 0x8e, 0x95, 0x98, 0x7b, 0xa4, 0x63, 0x8f, 0xa1,
	0x93, 0xa2, 0xd0, 0x9a, 0xc8, 0x27, 0xa3, 0x0a, 0x9d, 0x85, 0x76, 0x0e, 0xea, 0xfc, 0xde, 0x13,
	0x68, 0x2e, 0x74, 0x6c, 0x0b, 0x2a, 0x57, 0x38, 0xb7, 0x4b, 0xd0, 0x8f, 0xfa, 0x6e, 0xcc, 0x78,
	0x94, 0xe5, 0x97, 0xc6, 0x04, 0x4f, 0xcb, 0x3f, 0x95, 0xdc, 0x17, 0x50, 0x3f, 0x10, 0x8a, 0x5a,
	0xf9, 0x0b, 0xd4, 0xb9, 0x79, 0xb4, 0x6f, 0xff, 0x41, 0x7b, 0x9d, 0x6b, 0xdc, 0x33, 0xd8, 0xd4,
	0xe8, 0xeb, 0x64, 0xc1, 0xb1, 0x5d, 0xa8, 0x6b, 0x91, 0xbf, 0xe8, 0x47, 0x4d, 0x87, 0xa7, 0x01,
	0x73, 0xa1, 0x43, 0x04, 0x1d, 0x2d, 0x4d, 0x9b, 0x75, 0xb5, 0xb2, 0x5c, 0x7a, 0x1a, 0xb8, 0x07,
	0xd0, 0x32, 0x7e, 0xd4, 0xf0, 0x62, 0xaf, 0x87, 0xd0, 0xa0, 0xbd, 0xb8, 0xb1, 0xa9, 0x53, 0x7c,
	0x1a, 0xb8, 0x7f, 0x43, 0x55, 0x9f, 0x94, 0x75, 0xb4, 0x8c, 0x41, 0x55, 0xcd, 0x53, 0xb4, 0xd3,
	0x84, 0x9e, 0x99, 0x03, 0xf5, 0xb1, 0xc0, 0x20, 0x54, 0x92, 0xe6, 0x48, 0xd9, 0xcb, 0x43, 0x37,
	0x84, 0xed, 0x43, 0x81, 0x5c, 0xa1, 0xae, 0xe7, 0xe1, 0x3f, 0x19, 0x4a, 0xc5, 0xbe, 0x85, 0xaa,
	0x3e, 0x64, 0x54, 0xb3, 0xb5, 0xbf, 0xbb, 0xa2, 0x9b, 0x94, 0x4d, 0x49, 0xfa, 0x6a, 0x66, 0x69,
	0xa0, 0x7b, 0xeb, 0xe7, 0x35, 0xca, 0x54, 0xa3, 0x6b, 0xe1, 0x43, 0x5b, 0xea, 0x0a, 0xd8, 0xed,
	0x52, 0x32, 0x4d, 0x62, 0x89, 0xec, 0x3b, 0x60, 0xb9, 0x9c, 0x86, 0xdd, 0x38, 0xc9, 0x62, 0x45,
	0x95, 0x37, 0xbc, 0x2d, 0xcb, 0x68, 0xc1, 0xa1, 0xc6, 0x3f, 0xb8, 0xd8, 0xfe, 0xbf, 0x0d, 0xb3,
	0x0b, 0x17, 0x66, 0x3e, 0xb3, 0x67, 0x00, 0xa6, 0x38, 0x8d, 0xe7, 0x55, 0xaf, 0xa4, 0x89, 0x5e,
	0x11, 0xc1, 0x7e, 0x86, 0xfa, 0x08, 0xd5, 0x9a, 0xe2, 0x5f, 0x01, 0x2e, 0x69, 0x79, 0xf7, 0xeb,
	0x57, 0x5d, 0xda, 0xe3, 0x69, 0xaa, 0xe6, 0xda, 0xe0, 0x08, 0x23, 0x5c, 0xdf, 0xe0, 0x25, 0xb4,
	0x4e, 0x68, 0x50, 0x9a, 0xf3, 0xed, 0x16, 0x38, 0xdc, 0xba, 0x03, 0xf7, 0x98, 0xbd, 0x82, 0xce,
	0x65, 0x3c, 0xf9, 0x68, 0x76, 0xbf, 0xc3, 0xd6, 0x41, 0x10, 0x9c, 0xdc, 0x1e, 0xf8, 0xec, 0x51,
	0xa1, 0x23, 0xf1, 0xf7, 0xb8, 0x9d, 0xc3, 0x03, 0x0f, 0xa7, 0xc9, 0x0c, 0x3f, 0x96, 0xe1, 0x31,
	0xb4, 0x47, 0xa8, 0x6e, 0x06, 0x77, 0x61, 0xf7, 0x3f, 0x2b, 0xb8, 0x27, 0x46, 0x36, 0x82, 0xed,
	0x11, 0xaa, 0x93, 0xe5, 0xcf, 0x5a, 0xa1, 0xd7, 0xc3, 0xa2, 0xf9, 0x2d, 0xd9, 0x11, 0x74, 0x47,
	0xa8, 0xce, 0xaf, 0x63, 0xfb, 0x55, 0x58, 0xcf, 0xe5, 0x18, 0x36, 0x47, 0xa8, 0x28, 0x78, 0x11,
	0x4a, 0x95, 0x88, 0xf9, 0x5a, 0x36, 0xbf, 0xc1, 0x83, 0x11, 0xaa, 0x8b, 0x2c, 0x4d, 0x13, 0xa1,
	0x30, 0xc8, 0x27, 0x72, 0xa1, 0x55, 0x6f, 0x05, 0x91, 0x8b, 0xfe, 0xcc, 0xaf, 0x28, 0x8d, 0xbe,
	0x55, 0x1f, 0xc3, 0x3b, 0x93, 0xaa, 0xf7, 0xd5, 0x7b, 0xb2, 0xcc, 0x90, 0x79, 0x5e, 0xfb, 0xab,
	0xaa, 0xa9, 0x37, 0x35, 0xfa, 0x9b, 0xf6, 0xe3, 0xbb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x8b,
	0xae, 0x33, 0x15, 0x0a, 0x00, 0x00,
}
